### ISSUE TITLE
Verify that time is synced with server

### ISSUE THREAD

**Issue by redfast00** [12urenloop/manual-count-2#48]

**Comment by redfast00** [comment]
@NuttyShrimp in je PR zie ik dat je in `src/stores/time.store.ts` al een server vs client offset is, dat is al super nice :) Zou je juist nog willen zorgen dat dit ook in de frontend zichtbaar is, wat die offset is (eventueel in het rood als die meer dan pakt 3 seconden is)? Zo komen we geen onverwachte issues tegen, waarbij een client halverwege het event een NTP-sync doet en plots de tijd verkeerd is.

**Comment by NuttyShrimp** [comment]
Yes, zal ik doen

**Comment by NuttyShrimp** [comment]
Zo, in #49 is er ook een time tag toegevoegd waarin de offset te zien is. daarnaast heb ik ook een interval serversided toegevoegd die via onze socket de tijd om de minuut doorstuurt
