### ISSUE TITLE
feat(backend/laps): pushing missing laps from local DB to telraam

### ISSUE THREAD

**Issue by NuttyShrimp** [12urenloop/manual-count-2#51]
We should add a function that check for all missing manual count laps in telraam and add it to our queue of laps.
Besides that it would be helpfull to hook it to a cmd to rerun it

- [ ] Add compareDB function to laps.service.ts
- [ ] Add new command `compareDB` to run the above function

**Comment by redfast00** [comment]
Could this function automatically run every n seconds?

**Comment by NuttyShrimp** [comment]
That is possible but I don't see any use cases behind it. If a lap returned an error it will be added to a queue and the system will try to push it at a later moment

**Comment by redfast00** [comment]
If the sync is automatic, we can't forget to run the sync command
