### ISSUE TITLE
feat(frontend): vibrate on mobile device after a successfull push

### ISSUE THREAD

**Issue by NuttyShrimp** [12urenloop/manual-count-2#54]
There was a recommendation to add a vibration after a lap was successfully pushed to the backend to make it easier to distinguish if a lap was actually pushed when the time on the teamcomponent is removed.
We can use the `useVibrate` function from vueUse to make our live easy [docs](https://vueuse.org/core/usevibrate/#usevibrate)

- [x] Add vibration after a successfull push

**Comment by redfast00** [comment]
Good idea! This should ideally also be toggle-able from the frontend per-device, so if people don't like the vibration, they can turn it off for them.
