### ISSUE TITLE
Race condition: dubbele rondes

### ISSUE THREAD

**Issue by redfast00** [12urenloop/manual-count-2#56]
Dit jaar, op 6urenloop, hebben we gezien dat er heel soms een rondetijd van 0 seconden was op manualcount, een dubbel rondje dus. Misschien dat dit door een racecondition komt: ik denk dat we met meerdere toestellen aan het tellen waren.

**Comment by redfast00** [comment]
We hebben toen commit 3e8d48629755318d40b4e254449292164bc3a1f4 gedraaid

**Comment by klaasg** [comment]
Zou ook kunnen aan de monitoring liggen (telraam endpoint of grafana zelf).

Dat was te zien in het Lap Times dashboard (https://github.com/12urenloop/monitoring/commit/f2f56a1da01091911d17bd43430614313d770a05). En valt dus te repliceren met de 6ul database dump

**Comment by NuttyShrimp** [comment]
I think we can be even more cautious with adding a queue system to the lap registration system. I think it is possible to send duplicated laps if users send the api request almost at the same time
